# Generated by Django 5.1 on 2024-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganicFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='special_offers',
            name='category',
            field=models.CharField(choices=[('all offers', 'All Offer'), ('fruits', 'Fruits'), ('vegatables', 'Vegatables')], max_length=50),
        ),
    ]
