# Generated by Django 5.1 on 2024-09-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganicFoodApp', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_offers',
            name='category',
            field=models.CharField(choices=[('all offers', 'All Offer'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables')], max_length=50),
        ),
    ]
