# Generated by Django 5.1 on 2024-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganicFoodApp', '0004_alter_special_offers_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_offers',
            name='category',
            field=models.CharField(choices=[('all offers', 'All Offer'), ('fruits', 'Fruits'), ('vegatables', 'Vegatables')], max_length=50),
        ),
    ]
