# Generated by Django 5.1 on 2024-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default='', upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.CharField(max_length=50),
        ),
    ]
